---
- name: Ensure necessary packages for repository management are installed (Debian)
  ansible.builtin.package:
    name: ["apt-transport-https", "wget"]
    state: present
  when: ansible_os_family == 'Debian'

# --- Kibana Installation (Elastic Stack) ---
- name: Import Elastic GPG Key (Debian)
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Elastic Repository (Debian)
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Kibana (Debian)
  ansible.builtin.apt:
    name: kibana
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Elastic Repository (CentOS/RHEL)
  ansible.builtin.yum_repository:
    name: elastic-8.x
    description: Elastic repository for 8.x packages
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Install Kibana (CentOS/RHEL)
  ansible.builtin.dnf:
    name: kibana
    state: present
  when: ansible_os_family == 'RedHat'

# --- Kibana Configuration ---
# Configures Kibana to connect to the external Elasticsearch host defined in config.yaml.
- name: Configure Kibana (kibana.yml)
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^{{ item.key }}:'
    line: "{{ item.key }}: {{ item.value }}"
    create: yes
    owner: kibana
    group: kibana
    mode: '0660'
  loop:
    - { key: 'server.port', value: 5601 }
    - { key: 'server.host', value: '"0.0.0.0"' }
    - { key: 'elasticsearch.hosts', value: "['http://{{ elasticsearch_host }}:9200']" }
  notify: Restart Kibana Service

- name: Enable and Start Kibana service
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: yes
